export const TIERS = {
  starter: {
    name: 'Starter',
    price: 29,
    currency: 'USD',
    limits: {
      scansPerMonth: 500,
      sources: ['linkedin', 'website', 'reddit'],
      emailsPerMonth: 100,
      followUpSteps: 1,
      crmConnections: 0,
      slackAlerts: false,
      teamMembers: 1,
      apiAccess: false,
      whiteLabel: false,
      dedupLevel: 'basic',
      aiScoring: 'basic',
      aiInsights: 'basic',
      messageTemplates: 10,
      nurtureSequences: 1,
      dataRetentionDays: 30,
    },
  },

  pro: {
    name: 'Pro',
    price: 79,
    currency: 'USD',
    limits: {
      scansPerMonth: 2500,
      sources: ['linkedin', 'facebook', 'reddit', 'twitter', 'website', 'google_maps'],
      emailsPerMonth: 1000,
      followUpSteps: 5,
      crmConnections: 1,
      slackAlerts: true,
      teamMembers: 3,
      apiAccess: false,
      whiteLabel: false,
      dedupLevel: 'cross-source',
      aiScoring: 'advanced',
      aiInsights: 'advanced',
      messageTemplates: 50,
      nurtureSequences: 5,
      dataRetentionDays: 90,
    },
  },

  scale: {
    name: 'Scale',
    price: 199,
    currency: 'USD',
    limits: {
      scansPerMonth: 10000,
      sources: [
        'linkedin',
        'facebook',
        'reddit',
        'twitter',
        'instagram',
        'website',
        'google_maps',
        'news',
        'apollo',
      ],
      emailsPerMonth: 5000,
      followUpSteps: 'unlimited',
      crmConnections: 'unlimited',
      slackAlerts: true,
      teamMembers: 10,
      apiAccess: true,
      whiteLabel: true,
      dedupLevel: 'historical',
      aiScoring: 'advanced',
      aiInsights: 'advanced',
      messageTemplates: 'unlimited',
      nurtureSequences: 'unlimited',
      dataRetentionDays: 365,
    },
  },
};